---
title: "Differential accessibility analysis"
output: html_notebook
---




Plotting scritp functions

#plotting script
```{r}

FindRegion(object=human_all_atac,assay = "cre",region = "NKX2-1")


  # region can be a string, name of a gene, or GRanges object
FindRegion <- function(
  object,
  region,
  sep = c("-", "-"),
  assay = NULL,
  extend.upstream = 0,
  extend.downstream = 0
) {
  if (!is(object = region, class2 = "GRanges")) {
    # if separators are present in the string and we can convert the
    # start to a number, assume we're using genomic coordinates
    if (all(sapply(X = sep, FUN = grepl, x = region))) {
      print("here")
      region <- StringToGRanges(regions = region, sep = sep)
    } else {
      region <- LookupGeneCoords(object = object, assay = assay, gene = region)
      if (is.null(x = region)) {
        stop("Gene not found")
      }
    }
  }
  
  region <- suppressWarnings(expr = Extend(
    x = region,
    upstream = extend.upstream,
    downstream = extend.downstream
  )
  )
  return(region)
}

plot_combined_cross_species<-function(gene,gene_mouse=NULL,upstr=1000,downstr=1000,plot_by="handannot",motif.names=NULL,highlight_human_reg=NULL,highlight_mouse_reg=NULL,validate=F){
  fname<-substring(gene, 1,1)
  sname<-substring(gene, 2)
  if(is.null(gene_mouse)) 
  {
  gene_mouse<-paste0(toupper(fname),tolower(sname))
  }
  gene_human<-toupper(gene)
  


 # reg_h<-FindRegion(object = human_all_atac,region = gene_human,extend.downstream = downstr,extend.upstream = upstr,assay = "cre")
#  reg_m<-FindRegion(object = mouse_select_atac,region = gene_mouse,extend.downstream = downstr,extend.upstream = upstr,assay = "mm10")
  
  reg_h <- LookupGeneCoords(object = human_all_atac,gene = gene_human,assay = "cre")
  reg_h <- suppressWarnings(expr = Extend(x = reg_h, upstream = upstr,downstream = downstr))
  
  reg_m <- LookupGeneCoords(object = mouse_select_atac,gene = gene_mouse,assay = "mm10")
  reg_m <- suppressWarnings(expr = Extend(x = reg_m, upstream = upstr,downstream = downstr))
  
  
  
  #findOverlaps(subject=reg_h,query = highlight_human_reg)
  
  print(paste0("plotting gene: ", gene))
  print(paste0("plotting human: ", gene_human," human: ",reg_h))
  print(paste0("plotting mouse: ", gene_mouse," mouse: ",reg_m))
  mm10_phylp="/brahms/torkenczyk/H_M_storage/conservation_tracks/mm10.60way.phyloP60way.bw"
  hg38_phylp="/brahms/torkenczyk/H_M_storage/conservation_tracks/hg38.phyloP100way.bw"
  mm10_lecif="/brahms/torkenczyk/H_M_storage/conservation_tracks/mm10.hg38.LECIF.srt.median.bw"
  hg38_lecif="/brahms/torkenczyk/H_M_storage/conservation_tracks/hg38.mm10.LECIF.srt.median.bw"
 # conservation_mm10<-BigwigTrack(region = reg_m,bigwig = mm10_phylp,type = 'heatmap')
  #conservation_hg38<-BigwigTrack(region = reg_h,bigwig = hg38_phylp,type = 'heatmap')
  
  # hg38_A549_a="/home/torkenczyk/H_M_chromatin_atlas/validation_sets/A459/GSM3137776_ENCFF631HEX_signal_of_unique_reads_GRCh38.bigWig"
   #hg38_A549_b="/home/torkenczyk/H_M_chromatin_atlas/validation_sets/A459/GSM3137777_ENCFF103COS_signal_of_unique_reads_GRCh38.bigWig"
   #hg38_A549_c="/home/torkenczyk/H_M_chromatin_atlas/validation_sets/A459/GSM3137778_ENCFF957GCK_signal_of_unique_reads_GRCh38.bigWig"
  
   
   
  if(!is.null(motif.names)){
  print("Adding Motifs")
  print("For Hg38")
  ls<-unlist(GetMotifData(object = human_all_atac, assay = "cre", slot = "motif.names"))
  motif_labels<-names(ls[match(motif.names,ls)])
  M<-GetMotifData(human_all_atac, assay = "cre")[,motif_labels]
  M2<-apply(M,2,function(x){which(x>0)})
  M2n<-apply(M,2,function(x){which(x==0)})

  
  Mdf<-data.frame(motifs=rep("",times=length(row.names(M))))
  M<-as.matrix(M)
  for (mt in names(M2)){
    c_ct<-match(mt,colnames(M))
    mt_n<-ls[match(mt,names(ls))]
    M[M2[[mt]],c_ct]<-mt_n
    M[M2n[[mt]],c_ct]<-""
  }
  M<-as.data.frame(M)
  M <- M %>% unite(motif, colnames(M), sep = ',')
  M$motif<-gsub(M$motif,perl=T,pattern = ",{2,}",replacement = "")
  M$motif<-gsub(M$motif,perl=T,pattern = "^,",replacement = "")
  M$motif<-gsub(M$motif,perl=T,pattern = ",$",replacement = "")
  M$motif[which(M$motif=="")]<-"No motif"
  
  human_all_atac[["cre"]]<-AddMetaData(human_all_atac[["cre"]],M)
  mouse_select_atac[["cre"]]<-AddMetaData(mouse_select_atac[["cre"]],M)
  
  print("For MM10")
  ls<-unlist(GetMotifData(object = mouse_select_atac, assay = "mm10", slot = "motif.names"))
  motif_labels<-names(ls[match(motif.names,ls)])
  M<-GetMotifData(mouse_select_atac,assay = "mm10")[,motif_labels]
  M2<-apply(M,2,function(x){which(x>0)})
  M2n<-apply(M,2,function(x){which(x==0)})
  Mdf<-data.frame(motifs=rep("",times=length(row.names(M))))
  M<-as.matrix(M)
  for (mt in names(M2)){
    c_ct<-match(mt,colnames(M))
    mt_n<-ls[match(mt,names(ls))]
    M[M2[[mt]],c_ct]<-mt_n
    M[M2n[[mt]],c_ct]<-""
  }
  M<-as.data.frame(M)
  M <- M %>% unite(motif, colnames(M), sep = ',')
  M$motif<-gsub(M$motif,perl=T,pattern = ",{2,}",replacement = "")
  M$motif<-gsub(M$motif,perl=T,pattern = "^,",replacement = "")
  M$motif<-gsub(M$motif,perl=T,pattern = ",$",replacement = "")
  #M$motif<-gsub(M$motif,perl=T,pattern = ",No motif$",replacement = "")
  M$motif[which(M$motif=="")]<-"No motif"
  mouse_select_atac[["mm10"]]<-AddMetaData(mouse_select_atac[["mm10"]],M)
  
  mouse1<-CoveragePlot(
    object = mouse_select_atac,links = F,assay ="mm10",
    group.by=plot_by,
    region = gene_mouse,
    annotation=T,peaks=T,
    extend.upstream = upstr,
    extend.downstream = downstr,bigwig = list(mm10_phylp,mm10_lecif),bigwig.type = 'heatmap',peaks.group.by = "motif", region.highlight = highlight_mouse_reg
  )
  
  mouse2<-CoveragePlot(
    object = mouse_select_atac,links = F,assay ="cre",
    group.by=plot_by,
    region = gene_human,
    annotation=T,peaks=T,
    extend.upstream = upstr,
    extend.downstream = downstr,bigwig = list(hg38_phylp,hg38_lecif),bigwig.type = 'heatmap',peaks.group.by = "motif",region.highlight = highlight_human_reg
  )
  
  human<-CoveragePlot(
    object = human_all_atac, 
    group.by=plot_by,region = gene_human,assay ="cre",
    extend.upstream = upstr,
    extend.downstream = downstr,annotation=T,peaks=T,bigwig = list(hg38_phylp,hg38_lecif),bigwig.type = 'heatmap',peaks.group.by = "motif", region.highlight = highlight_human_reg
  )
  
  
  } else {
  
  
  mouse1<-CoveragePlot(
    object = mouse_select_atac,links = F,assay ="mm10",
    group.by=plot_by,
    region = reg_m,
    annotation=T,peaks=T,
    extend.upstream = upstr,
    extend.downstream = downstr,bigwig = list(mm10_phylp,mm10_lecif),bigwig.type = 'heatmap', region.highlight = highlight_mouse_reg
  )
  
  mouse2<-CoveragePlot(
    object = mouse_select_atac,links = F,assay ="cre",
    group.by=plot_by,
    region = reg_h,
    annotation=T,peaks=T,
    extend.upstream = upstr,
    extend.downstream = downstr,bigwig = list(hg38_phylp,hg38_lecif),bigwig.type = 'heatmap',region.highlight = highlight_human_reg
  )
  
    mouse2b<-CoveragePlot(
    object = mouse_select_atac,links = F,assay ="cre",
    group.by=plot_by,
    region = reg_h,
    annotation=F,peaks=F,
    extend.upstream = upstr,
    extend.downstream = downstr,region.highlight = highlight_human_reg)
  
  human<-CoveragePlot(
    object = human_all_atac, 
    group.by=plot_by,region = reg_h,assay ="cre",
    extend.upstream = upstr,
    extend.downstream = downstr,annotation=T,peaks=T,bigwig = list(hg38_phylp,hg38_lecif),bigwig.type = 'heatmap',region.highlight = highlight_human_reg
  )
  
  humanb<-CoveragePlot(
    object = human_all_atac, 
    group.by=plot_by,region = reg_h,assay ="cre",
    extend.upstream = upstr,
    extend.downstream = downstr,annotation=T,peaks=T,bigwig = list(hg38_A549_a,hg38_A549_b,hg38_A549_c),bigwig.type = "coverage",region.highlight = highlight_human_reg
  )
 
  }
  
  
    plots2<-wrap_plots(list(mouse2b,human), ncol = 1, heights = c(8,10))
    print(paste0("plotting gene: ", gene))
    png(filename = paste0("/brahms/torkenczyk/H_M_storage/",gene,"_combined.wcons_yaxe2.png"),width = 20,height=18,units = "cm",res=300)
    print(plots2)
    dev.off()
    ggsave(plot = plots2,filename = paste0("/brahms/torkenczyk/H_M_storage/paper_pdfs/",gene,"_combined.wcons_yaxe.pdf"),width = 10,height=18,units = "cm")
    print("THIS")
    plots<-wrap_plots(list(mouse1,mouse2,human), ncol = 3, widths  = c(10,10,10))
    png(filename = paste0("/brahms/torkenczyk/H_M_storage/",gene,"_combined.wcons2.png"),width = 30,height=25,units = "cm",res=300)
    print(wrap_plots(list(mouse1,mouse2,human), ncol = 3, widths  = c(10,10,10)))
    dev.off()
    
    
    
    if (validate==T){
    #with mouse
      print("Plotting validation of mouse")
    DefaultAssay(M_subset)<-"peaks"
    
    mouse2c<-CoveragePlot(
    object = M_subset,links = F,assay ="peaks",
    group.by="cell_type",
    region = reg_m,
    annotation=F,peaks=F,
    extend.upstream = upstr,
    extend.downstream = downstr,region.highlight = highlight_mouse_reg)
    plots3<-wrap_plots(list(mouse2c,mouse1), ncol = 1, heights = c(8,10))
    
    png(filename = paste0("/brahms/torkenczyk/H_M_storage/",gene,"_combined.wcons_yaxe_mouse_VAL.png"),width = 20,height=18,units = "cm",res=300)
    print(plots3)
    dev.off()
    
    #with human
    
    print("Plotting validation of human")
    DefaultAssay(integrated)<-"bins"
    
    human_v<-CoveragePlot(object = integrated, 
    group.by="cluster_name",region = reg_h,assay ="bins",
    extend.upstream = upstr,
    extend.downstream = downstr,annotation=F,peaks=F,region.highlight = highlight_human_reg)
   
    plots4<-wrap_plots(list(human_v,humanb), ncol = 1, heights = c(8,14))
    print("THIS")
    png(filename = paste0("/home/torkenczyk/H_M_chromatin_atlas/validation_sets/A459/plots/",gene,"_combined.wcons_yaxe_human_VAL.png"),width = 20,height=28,units = "cm",res=300)
    print(plots4)
    dev.off()
    print("THIS2")
    png(filename = paste0("/brahms/torkenczyk/H_M_storage/",gene,"_combined.wcons_yaxe_human_VAL.png"),width = 20,height=28,units = "cm",res=300)
    print(plots4)
    dev.off()
    
    }
    
   return(plots2)
}


```



Read in the human and mouse datasets
```{r}

library(presto)
library(Signac)
library(Seurat)

human_all_atac<-readRDS("/brahms/torkenczyk/H_M_storage/analysis/objects/Select_human_tissues.rds")
mouse_select_atac<-readRDS("/brahms/torkenczyk/H_M_storage/analysis/objects/Select_mouse_tissues.rds")



```



#running DA
```{r}

markers_h <- presto:::wilcoxauc.Seurat(X = human_all_atac,assay = 'data', seurat_assay = 'cre',min.pct = 0)
markers_filt_h<-markers_h[markers_h$padj<0.05 & markers_h$logFC > 0,]

markers_m <- presto:::wilcoxauc.Seurat(X = mouse_select_atac,assay = 'data', seurat_assay = 'cre',min.pct = 0)
markers_filt_m<-markers_m[markers_m$padj<0.05 & markers_m$logFC > 0,]

markers_m_mm9 <- presto:::wilcoxauc.Seurat(X = mouse_select_atac,assay = 'data', seurat_assay = 'mm9',min.pct = 0)
markers_m_mm10 <- presto:::wilcoxauc.Seurat(X = mouse_select_atac,assay = 'data', seurat_assay = 'mm10',min.pct = 0)


```


#common da and species specific
```{r}
library("ggVennDiagram")
da.peaks<-list()
for (i in (levels(as.factor(markers_h$group))))
  {
  m_h<-filter(markers_filt_h,group==i)
  m_m<-filter(markers_filt_m,group==i)
  x=list(human=m_h$feature,mouse=m_m$feature)
  da.peaks[[i]]<-ggVennDiagram(x)+ggtitle(label = i)
  
}

wrap_plots(da.peaks,ncol=3,nrow = 5)


#lifted over peaks
hg38tomm9peaks<-read.table(file="/brahms/torkenczyk/H_M_storage/analysis/Mouse_hg38_0.1_peaks.bed",header = F)
mm10tomm9peaks<-read.table(file="/brahms/torkenczyk/H_M_storage/analysis/Mouse_mm10_peaks.bed",header = F)
hg38tomm9peaks$feature_hg38<-paste(hg38tomm9peaks$V1,hg38tomm9peaks$V2,hg38tomm9peaks$V3,sep = "-")

mm10tomm9peaks$feature_mm10<-paste(mm10tomm9peaks$V1,mm10tomm9peaks$V2,mm10tomm9peaks$V3,sep = "-")
mm10tomm9peaks$feature_mm9<-gsub(mm10tomm9peaks$V4,pattern = "_",replacement = "-")
mm10tomm9peaks$V1<-NULL
mm10tomm9peaks$V2<-NULL
mm10tomm9peaks$V3<-NULL
mm10tomm9peaks$V4<-NULL

hg38tomm9peaks$feature_mm9<-gsub(hg38tomm9peaks$V4,pattern = "_",replacement = "-")
hg38tomm9peaks$V1<-NULL
hg38tomm9peaks$V2<-NULL
hg38tomm9peaks$V3<-NULL
hg38tomm9peaks$V4<-NULL


hg38tomm9peaks<-merge(hg38tomm9peaks,mm10tomm9peaks,by="feature_mm9")

mm9hg38logplots<-list()


#between mm9 and hg38
mousehumanlogplotsmm9<-list()
#between hg38 and hg38
mousehumanlogplotshg38<-list()
mouse_DA<-list()
human_DA<-list()
shared_DA<-list()
muse<-list()

for (i in (levels(as.factor(markers_h$group))))
  {
  print(i)

  m_h<-dplyr::filter(markers_h,group==i)
  m_m<-dplyr::filter(markers_m,group==i)
  m_m9<-dplyr::filter(markers_m_mm9,group==i)
  m_m9$feature_mm9=m_m9$feature
  m_m9<-merge(x=m_m9,y=hg38tomm9peaks,by="feature_mm9")
  m_m9$feature<-m_m9$feature_hg38
  
  matched<-findOverlaps(query=StringToGRanges(m_m9$feature),subject=StringToGRanges(m_m$feature))
  matched2<-findOverlapPairs(StringToGRanges(m_m9$feature),StringToGRanges(m_m$feature))
  #most 1on1 table(table(subjectHits(matched))>1) FALSE  196781 TRUE    8957 
  #most 1on1 table(table(queryHits(matched))>1) FALSE  123577 TRUE    39548 
  #matched2[as.vector(table(subjectHits(matched))>1) | as.vector(table(queryHits(matched))>1),]
  m_m9<-m_m9[queryHits(matched),]
  m_m9$feature_hg38matched<-m_m$feature[subjectHits(matched)]
  m_m9$logFC_hg38matched<-m_m$logFC[subjectHits(matched)]
  m_m9$avgExpr_hg38matched<-m_m$avgExpr[subjectHits(matched)]
  m_m9$auc_hg38matched<-m_m$auc[subjectHits(matched)]
  m_m9$padj_hg38matched<-m_m$padj[subjectHits(matched)]
  m_m9$pct_in_hg38matched<-m_m$pct_in[subjectHits(matched)]
  m_m9$pct_out_hg38matched<-m_m$pct_out[subjectHits(matched)]
  
  #first let us see if these values correlate
 # mm9hg38logplots[[i]]<-ggplot(m_m9,aes(y=logFC_hg38matched,x=logFC))+geom_point()+theme_classic()+ggtitle(i)+ylab("hg38 calculated logFC")+xlab("mm9 calculated logFC")
  m_m9$feature<-m_m9$feature_hg38matched
  
  mu<-merge(x=m_m9,y=m_h,by="feature",all.x=T)
  mu<-mu[with(mu, order(-logFC.x)),]
  mu$rank.mouse<-c(1:length(mu$logFC.x))
  mu<-mu[with(mu, order(-logFC.y)),]
  mu$rank.human=c(1:length(mu$logFC.y))
  #this is a rough ordering
  mu$rankavg<-(mu$rank.mouse+mu$rank.human)/2
  mu$rankdiff.mouse<-mu$rank.mouse-mu$rank.human
  mu$rankdiff.human<-mu$rank.human-mu$rank.mouse
  if(i=="Schwann_cells" )
  {
  top_num_peaks=700
  }else{top_num_peaks=1000}
  #select where one is significant at least (this is not necessary when you need more peaks)
  mu<-mu[mu$padj.x<0.05 | mu$padj.y<0.05 | mu$padj_hg38matched<0.05,]
  mu<-mu[with(mu, order(rankavg)),]
  mu$category<-c(rep("shared",times=top_num_peaks),rep("other",times=length(mu$feature_mm9)-top_num_peaks))
  mu<-mu[with(mu, order(rank.human)),]
  #also did this with 0.05, for the 10K we had to lower the threshold
  mu$category[head(which(mu$category != "shared" & mu$logFC.y > 0 & mu$padj.x > 0.000001),n=top_num_peaks)]<-rep("human",times=top_num_peaks)
  mu<-mu[with(mu, order(rank.mouse)),]
  mu$category[head(which(mu$category != "shared" & mu$logFC.x > 0 & mu$category != "human" & mu$padj.y > 0.000001),n=top_num_peaks)]<-rep("mouse",times=top_num_peaks)
  
  
  #first let us see if these values correlate
 # mousehumanlogplotsmm9[[i]]<-ggplot(mu,aes(x=logFC.x,y=logFC.y,color=category))+geom_point()+theme_classic()+ggtitle(i)+ylab("Human logFC")+xlab("Mouse mm9 calculated logFC")
  
  #first let us see if these values correlate
#  mousehumanlogplotshg38[[i]]<-ggplot(mu,aes(x=logFC_hg38matched,y=logFC.y,color=category))+geom_point()+theme_classic()+ggtitle(i)+ylab("Human logFC")+xlab("Mouse hg38 calculated logFC")
  
  mouse_DA[[i]]<- mu[which(mu$category=="mouse"),]
  human_DA[[i]]<- mu[which(mu$category=="human"),]
  shared_DA[[i]]<- mu[which(mu$category=="shared"),]
  
  #what if we divide into quartiles (will be percetile)
  
  mu$m_quantile <- with(mu, factor(findInterval( logFC_hg38matched, c(-Inf,
                               quantile(logFC_hg38matched, probs=c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9)), Inf)), labels=c("M1","M2","M3","M4","M5","M6","M7","M8","M9","M10")))
  
  mu$h_quantile <- with(mu, factor(findInterval( logFC.y, c(-Inf,
                               quantile(logFC.y, probs=c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9)), Inf)), labels=c("H1","H2","H3","H4","H5","H6","H7","H8","H9","H10")))
  
  mu$quantile_comb<-paste(mu$m_quantile,mu$h_quantile,sep = "_")
 
  muse[[i]]=mu
  
  
  
}


wrap_plots(mousehumanlogplotsmm9,ncol=4,nrow = 4)
wrap_plots(mousehumanlogplotshg38,ncol=4,nrow = 3)


ClosestFeature(mouse_select_atac,regions = pn_m$feature)

ClosestFeature(human_all_atac,regions = shared_DA$`Smooth muscle cells`$feature)
ho<-ClosestFeature(human_all_atac,regions = human_DA$`Smooth muscle cells`$feature)
mo<-ClosestFeature(human_all_atac,regions = mouse_DA$`Smooth muscle cells`$feature)




#this was only for the writeout downstream we should stick to the original

for (i in (levels(as.factor(markers_h$group))))
  {
  a<-names(human_DA[[i]])
  a<-gsub(a,pattern = "\\.x",replacement = ".mm9")
  a<-gsub(a,pattern = "feature_hg38",replacement = "mm9_lifted_hg38peak")
  a<-gsub(a,pattern = "feature_mm10",replacement = "mm9_lifted_mm10peak")
  a<-gsub(a,pattern = "feature_mm10",replacement = "mm9_lifted_mm10peak")
  a<-gsub(a,pattern = "\\.y",replacement = ".hg38")
  
  a<-paste(a,c("hg38_universal",rep("mouse",times=19),rep("human",times=9),rep("categorization",times=6)),sep = "_")
  names(human_DA[[i]])<-a
  names(shared_DA[[i]])<-a
  names(mouse_DA[[i]])<-a
  
}


for (i in (levels(as.factor(markers_h$group))))
  {
  a<-names(muse[[i]])
  a<-gsub(a,pattern = "\\.x",replacement = ".mm9")
  a<-gsub(a,pattern = "feature_hg38",replacement = "mm9_lifted_hg38peak")
  a<-gsub(a,pattern = "feature_mm10",replacement = "mm9_lifted_mm10peak")
  a<-gsub(a,pattern = "feature_mm10",replacement = "mm9_lifted_mm10peak")
  a<-gsub(a,pattern = "\\.y",replacement = ".hg38")
  
  a<-paste(a,c("hg38_universal",rep("mouse",times=19),rep("human",times=9),rep("categorization",times=6)),sep = "_")
  names(muse[[i]])<-a
}  
  





save(shared_DA, file="/brahms/torkenczyk/H_M_storage/analysis/objects/DA_info/Shared.bw.species.DA.RData")
save(mouse_DA, file="/brahms/torkenczyk/H_M_storage/analysis/objects/DA_info/Mouse_only.bw.species.DA.RData")
save(human_DA, file="/brahms/torkenczyk/H_M_storage/analysis/objects/DA_info/Human_only.bw.species.DA.RData")
saveRDS(muse,file = "/brahms/torkenczyk/H_M_storage/analysis/objects/DA_info/All_da_continous_info.rds")

#match with data from bing REN

a<-read.table("/brahms/torkenczyk/H_M_storage/cCRE_Accessibility.tsv.gz")

ctg<-levels(as.factor(na.omit(human_all_atac[[]]$Abbreviation)))

match(ctg,names(a))


a<-a[,na.omit(match(ctg,names(a)))]

order(muse$`B-lymphocytes`$rankavg_categorization)[1:5000,]




row.names(a)<-gsub(pattern=":",replacement = "-",row.names(a))

b<-a[muse$`T-lymphocytes`[order(muse$`B-lymphocytes`$rankavg_categorization),][1:6000,]$feature_hg38_universal,]

Heatmap(t(scale(t(as.matrix(b)))),show_row_names = FALSE,cluster_columns = FALSE,cluster_rows = FALSE)


```

plot one gene that is an example of conservation for each celltype
```{r}

load("/brahms/torkenczyk/H_M_storage/analysis/objects/DA_info/Shared.bw.species.DA.RData")
shared_DA$Cardiomyocytes

upstr=5000
downstr=5000

reg_h <- LookupGeneCoords(object = human_all_atac,gene = "MYH7",assay = "cre")
reg_h <- suppressWarnings(expr = Extend(x = reg_h, upstream = upstr,downstream = downstr))
DA_str<-shared_DA$Cardiomyocytes$feature_hg38_universal
DA_gr<-StringToGRanges(DA_str,sep=c("-","-"))
DA_highlight<-DA_gr[queryHits(findOverlaps(query = DA_gr,subject = reg_h))]
p_card<-plot_combined_cross_species(gene = "MYH7",upstr = 5000,downstr = 5000,highlight_human_reg = DA_highlight)
reg_h <- LookupGeneCoords(object = human_all_atac,gene = "SHANK3",assay = "cre")
reg_h <- suppressWarnings(expr = Extend(x = reg_h, upstream = upstr,downstream = downstr))
DA_str<-shared_DA$`Endothelial cells`$feature_hg38_universal
DA_gr<-sort(StringToGRanges(DA_str,sep=c("-","-")))
a<-ClosestFeature(human_all_atac,DA_gr)
A<-unique(a[a$distance<5000,]$gene_name)
DA_highlight<-DA_gr[queryHits(findOverlaps(query = DA_gr,subject = reg_h))]
pend<-plot_combined_cross_species(gene = "SHANK3",upstr = 5000,downstr = 5000,highlight_human_reg = DA_highlight)
reg_h <- LookupGeneCoords(object = human_all_atac,gene = "SPARC",assay = "cre")
reg_h <- suppressWarnings(expr = Extend(x = reg_h, upstream = upstr,downstream = downstr))
DA_str<-shared_DA$`Smooth muscle cells`$feature_hg38_universal
DA_gr<-StringToGRanges(DA_str,sep=c("-","-"))
a<-ClosestFeature(human_all_atac,DA_gr)
A<-unique(a[a$distance<5000,]$gene_name)
DA_highlight<-DA_gr[queryHits(findOverlaps(query = DA_gr,subject = reg_h))]
psm<-plot_combined_cross_species(gene = "SPARC",upstr = 5000,downstr = 5000,highlight_human_reg = DA_highlight)
reg_h <- LookupGeneCoords(object = human_all_atac,gene = "MRC1",assay = "cre")
reg_h <- suppressWarnings(expr = Extend(x = reg_h, upstream = upstr,downstream = downstr))
DA_str<-shared_DA$Macrophages$feature_hg38_universal
DA_gr<-StringToGRanges(DA_str,sep=c("-","-"))
DA_highlight<-DA_gr[queryHits(findOverlaps(query = DA_gr,subject = reg_h))]
pmac<-plot_combined_cross_species(gene = "MRC1",upstr = 5000,downstr = 5000,highlight_human_reg = DA_highlight)

#continue here
a<-ClosestFeature(human_all_atac,DA_gr)

p2<-plot_combined_cross_species(gene = "MPRIP")
p3<-plot_combined_cross_species(gene = "MPRIP")
p3<-plot_combined_cross_species(gene = "CNN1")
p3<-plot_combined_cross_species(gene = "MYH11")
p3<-plot_combined_cross_species(gene = "ZFHX3")
p3<-plot_combined_cross_species(gene = "TAGLN")
p3<-plot_combined_cross_species(gene = "SEPT9")

c("MYH7","MYH6","SHANK3","SPARC","MPRIP","CNN1","MYH11","ZFHX3","TAGLN","SEPT9")

```



#confirm overlap
```{r}
PNmm9<-shared_DA$Pneumocytes$feature_mm9_mouse
PNmm9_m<-mouse_DA$Pneumocytes$feature_mm9_mouse
PNmm9_h<-human_DA$Pneumocytes$feature_mm9_mouse


int_bed<-data.frame(chr=str_split_fixed(PNmm9,"-",n=3)[,1],start=str_split_fixed(PNmm9,"-",n=3)[,2],end=str_split_fixed(PNmm9,"-",n=3)[,3])
write.table(int_bed,file = "/home/torkenczyk/LD/celltype_bedfiles/Shared2celline.mm9.Pneumocytes.bed",quote = F,sep = "\t",row.names = F,col.names = F)


int_bed<-data.frame(chr=str_split_fixed(PNmm9_h,"-",n=3)[,1],start=str_split_fixed(PNmm9_h,"-",n=3)[,2],end=str_split_fixed(PNmm9_h,"-",n=3)[,3])
write.table(int_bed,file = "/home/torkenczyk/LD/celltype_bedfiles/Uniq2celline.h.mm9.Pneumocytes.bed",quote = F,sep = "\t",row.names = F,col.names = F)


int_bed<-data.frame(chr=str_split_fixed(PNmm9_m,"-",n=3)[,1],start=str_split_fixed(PNmm9_m,"-",n=3)[,2],end=str_split_fixed(PNmm9_m,"-",n=3)[,3])
write.table(int_bed,file = "/home/torkenczyk/LD/celltype_bedfiles/Uniq2celline.m.mm9.Pneumocytes.bed",quote = F,sep = "\t",row.names = F,col.names = F)

filecount = "/home/torkenczyk/H_M_chromatin_atlas/human_data/verify_peaks/Mouse/ATACseq_Matrix/chromatin.accessibility.raw.count.txt"

#this analysis is in that folder


#scATAC-seq analysis

lung_extra<-Read10X_h5(filename = "verify_peaks/Mouse/GSM4795059_7wk-scATAC_filtered_peak_bc_matrix.h5")
a<-read10xCounts("verify_peaks/GSM4795059_7wk-scATAC_filtered_peak_bc_matrix.h5")
library(DropletUtils)


DefaultAssay(mouse_select_atac)<-"mm10"

peaks_mm10<-row.names(mouse_select_atac)
granges_mm10<-StringToGRanges(peaks_mm10)
file_mouseval<-'verify_peaks/Mouse/GSM4795059_7wk-scATAC_fragments.tsv.gz'
frags_mm10 <- CreateFragmentObject(
  path = file_mouseval, 
  validate.fragments = TRUE
)
cRE_peaks_mm10<- FeatureMatrix(
  fragments = frags_mm10,
  features = granges_mm10,
)

# I did not quantify but could technically call peaks -> just did


# extract gene annotations from EnsDb
annotations_mouse_mm10 <- GetGRangesFromEnsDb(ensdb = EnsDb.Mmusculus.v79)
# change to UCSC style since the data was mapped to mm
seqlevelsStyle(annotations_mouse_mm10) <- 'UCSC'
genome(annotations_mouse_mm10) <- "mm10"


mouse_select_atac[["mm10"]]<-CreateChromatinAssay(
  counts = cRE_peaks_mm10,
  genome = "mm10",
  ranges = mm10_peaks_granges,min.cells = 1,fragments = mm10_frags,annotation = annotations_mouse_mm10
)






```

#conservation of these site

```{r}

#check for conservation
bigwig_lecif<-"/brahms/torkenczyk/H_M_storage/analysis/conservation/hg38.mm10.LECIF.srt.median.bw"
bigwig_phyp<-"/brahms/torkenczyk/H_M_storage/analysis/conservation/hg38.phyloP100way.bw"
bigwig_phast<-"/brahms/torkenczyk/H_M_storage/analysis/conservation/hg38.phastCons100way.bw"
#check for unique mapping, ran this later
bigwig_mapability<-"/brahms/torkenczyk/H_M_storage/analysis/conservation/k50.Umap.MultiTrackMappability.bw"

region_value<-function(x,bigwig_compare){median(rtracklayer::import(con = bigwig_compare,which = StringToGRanges(x),as = "NumericList")[[1]])}
vregvalue<-Vectorize(region_value,"x")


median_cons_reg_score_phyp<-list()
median_uniq_reg_score_h_phyp<-list()
median_uniq_reg_score_m_phyp<-list()

median_cons_reg_score_lecif<-list()
median_uniq_reg_score_h_lecif<-list()
median_uniq_reg_score_m_lecif<-list()

median_cons_reg_score_phast<-list()
median_uniq_reg_score_h_phast<-list()
median_uniq_reg_score_m_phast<-list()

median_cons_reg_score_map<-list()
median_uniq_reg_score_h_map<-list()
median_uniq_reg_score_m_map<-list()

#include 10k sites
mouse_10_DA<-readRDS(file = "/brahms/torkenczyk/H_M_storage/analysis/objects/Mouse_sites_10k.rds")
human_10_DA<-readRDS(file = "/brahms/torkenczyk/H_M_storage/analysis/objects/Human_sites_10k.rds")
shared_10_DA<-readRDS(file = "/brahms/torkenczyk/H_M_storage/analysis/objects/Shared_sites_10k.rds")

#1k analysis
load(file = "/brahms/torkenczyk/H_M_storage/analysis/objects/DA_info/Shared.bw.species.DA.RData")
load(file = "/brahms/torkenczyk/H_M_storage/analysis/objects/DA_info/Human_only.bw.species.DA.RData")
load(file = "/brahms/torkenczyk/H_M_storage/analysis/objects/DA_info/Mouse_only.bw.species.DA.RData")




for (ct in names(human_DA)[3:13]){
print(ct)
clusth<-human_DA[[ct]]$feature_hg38_universal 
#clusth<-human_10_DA[[ct]]
clustm<-mouse_DA[[ct]]$feature_hg38_universal  
#clustm<-mouse_10_DA[[ct]]

int_ist<-shared_DA[[ct]]$feature_hg38_universal
#int_ist<-shared_10_DA[[ct]]

int_ist<-unique(GRangesToString(sort(StringToGRanges(int_ist))))
int_ist<-int_ist[which(as.character(seqnames(StringToGRanges(int_ist)))!="chrY")]

int_bed<-data.frame(chr=str_split_fixed(int_ist,"-",n=3)[,1],start=str_split_fixed(int_ist,"-",n=3)[,2],end=str_split_fixed(int_ist,"-",n=3)[,3])
write.table(int_bed,file = paste0("/home/torkenczyk/LD/celltype_bedfiles/Shared2celline.",ct,".latest.1k.bed"),quote = F,sep = "\t",row.names = F,col.names = F)
unint_ist_m<-unique(GRangesToString(sort(StringToGRanges(clustm))))
unint_ist_h<-unique(GRangesToString(sort(StringToGRanges(clusth))))

unint_ist_m<-unint_ist_m[which(as.character(seqnames(StringToGRanges(unint_ist_m)))!="chrY")]
unint_ist_h<-unint_ist_h[which(as.character(seqnames(StringToGRanges(unint_ist_h)))!="chrY")]
unintint_bed_h<-data.frame(chr=str_split_fixed(unint_ist_m,"-",n=3)[,1],start=str_split_fixed(unint_ist_m,"-",n=3)[,2],end=str_split_fixed(unint_ist_m,"-",n=3)[,3])
unintint_bed_m<-data.frame(chr=str_split_fixed(unint_ist_h,"-",n=3)[,1],start=str_split_fixed(unint_ist_h,"-",n=3)[,2],end=str_split_fixed(unint_ist_h,"-",n=3)[,3])
write.table(unintint_bed_h,file = paste0("/home/torkenczyk/LD/celltype_bedfiles/Uniq2celline.h.",ct,".latest.1k.bed"),quote = F,sep = "\t",row.names = F,col.names = F)
write.table(unintint_bed_m,file = paste0("/home/torkenczyk/LD/celltype_bedfiles/Uniq2celline.m.",ct,".latest.1k.bed"),quote = F,sep = "\t",row.names = F,col.names = F)
print(length(unint_ist_h))
print(length(unint_ist_m))
print(length(int_ist))

#B_cells Cardiomyocytes Endothelial_cells Enterocytes Fibroblasts Goblet_cells Hepatocytes Macrophages 
#Myofibroblasts Pneumocytes Schwann_cells

print("shared")
median_cons_reg_score_lecif[[ct]]<-vregvalue(x = int_ist,bigwig_compare = bigwig_lecif)
median_cons_reg_score_phast[[ct]]<-vregvalue(x = int_ist,bigwig_compare = bigwig_phast)
median_cons_reg_score_phyp[[ct]]<-vregvalue(x = int_ist,bigwig_compare = bigwig_phyp)
median_cons_reg_score_map[[ct]]<-vregvalue(x = int_ist,bigwig_compare = bigwig_mapability)

print("Mouse")
median_uniq_reg_score_m_lecif[[ct]]<-vregvalue(x = unint_ist_m,bigwig_compare = bigwig_lecif)
median_uniq_reg_score_m_phast[[ct]]<-vregvalue(x = unint_ist_m,bigwig_compare = bigwig_phast)
median_uniq_reg_score_m_phyp[[ct]]<-vregvalue(x = unint_ist_m,bigwig_compare = bigwig_phyp)
median_uniq_reg_score_m_map[[ct]]<-vregvalue(x = unint_ist_m,bigwig_compare = bigwig_mapability)

print("Human")
median_uniq_reg_score_h_lecif[[ct]]<-vregvalue(x = unint_ist_h,bigwig_compare = bigwig_lecif)
median_uniq_reg_score_h_phast[[ct]]<-vregvalue(x = unint_ist_h,bigwig_compare = bigwig_phast)
median_uniq_reg_score_h_phyp[[ct]]<-vregvalue(x = unint_ist_h,bigwig_compare = bigwig_phyp)
median_uniq_reg_score_h_map[[ct]]<-vregvalue(x = unint_ist_h,bigwig_compare = bigwig_mapability)

}



#10k
top_10k_cons_phast<-list()
top_10k_cons_phyp<-list()
top_10k_cons_lecif<-list()
#1k
top_1k_cons_phast<-list()
top_1k_cons_phyp<-list()
top_1k_cons_lecif<-list()
top_1k_cons_map<-list()

for (ct in names(human_DA)){
a<-data.frame(score=median_cons_reg_score_lecif[[ct]],annot=rep("Conserved",times=length(median_cons_reg_score_lecif[[ct]])),celltype=rep(ct,times=length(median_cons_reg_score_lecif[[ct]])))
b<-data.frame(score=median_uniq_reg_score_m_lecif[[ct]],annot=rep("Mouse",times=length(median_uniq_reg_score_m_lecif[[ct]])),celltype=rep(ct,times=length(median_uniq_reg_score_m_lecif[[ct]])))
c<-data.frame(score=median_uniq_reg_score_h_lecif[[ct]],annot=rep("Human",times=length(median_uniq_reg_score_h_lecif[[ct]])),celltype=rep(ct,times=length(median_uniq_reg_score_h_lecif[[ct]])))
top_1k_cons_lecif[[ct]]<-rbind(a,b,c)

a<-data.frame(score=median_cons_reg_score_phast[[ct]],annot=rep("Conserved",times=length(median_cons_reg_score_phast[[ct]])),celltype=rep(ct,times=length(median_cons_reg_score_phast[[ct]])))
b<-data.frame(score=median_uniq_reg_score_m_phast[[ct]],annot=rep("Mouse",times=length(median_uniq_reg_score_m_phast[[ct]])),celltype=rep(ct,times=length(median_uniq_reg_score_m_phast[[ct]])))
c<-data.frame(score=median_uniq_reg_score_h_phast[[ct]],annot=rep("Human",times=length(median_uniq_reg_score_h_phast[[ct]])),celltype=rep(ct,times=length(median_uniq_reg_score_h_phast[[ct]])))
top_1k_cons_phast[[ct]]<-rbind(a,b,c)

a<-data.frame(score=median_cons_reg_score_phyp[[ct]],annot=rep("Conserved",times=length(median_cons_reg_score_phyp[[ct]])),celltype=rep(ct,times=length(median_cons_reg_score_phyp[[ct]])))
b<-data.frame(score=median_uniq_reg_score_m_phyp[[ct]],annot=rep("Mouse",times=length(median_uniq_reg_score_m_phyp[[ct]])),celltype=rep(ct,times=length(median_uniq_reg_score_m_phyp[[ct]])))
c<-data.frame(score=median_uniq_reg_score_h_phyp[[ct]],annot=rep("Human",times=length(median_uniq_reg_score_h_phyp[[ct]])),celltype=rep(ct,times=length(median_uniq_reg_score_h_phyp[[ct]])))
top_1k_cons_phyp[[ct]]<-rbind(a,b,c)

a<-data.frame(score=median_cons_reg_score_map[[ct]],annot=rep("Conserved",times=length(median_cons_reg_score_map[[ct]])),celltype=rep(ct,times=length(median_cons_reg_score_map[[ct]])))
b<-data.frame(score=median_uniq_reg_score_m_map[[ct]],annot=rep("Mouse",times=length(median_uniq_reg_score_m_map[[ct]])),celltype=rep(ct,times=length(median_uniq_reg_score_m_map[[ct]])))
c<-data.frame(score=median_uniq_reg_score_h_map[[ct]],annot=rep("Human",times=length(median_uniq_reg_score_h_map[[ct]])),celltype=rep(ct,times=length(median_uniq_reg_score_h_map[[ct]])))
top_1k_cons_map[[ct]]<-rbind(a,b,c)


}

#10k
top_10k_cons_lecif_df<-Reduce(rbind,top_10k_cons_lecif)
top_10k_cons_phast_df<-Reduce(rbind,top_10k_cons_phast)
top_10k_cons_phyp_df<-Reduce(rbind,top_10k_cons_phyp)
top_10k_cons_map_df<-Reduce(rbind,top_10k_cons_phyp)
#1k
top_1k_cons_lecif_df<-Reduce(rbind,top_1k_cons_lecif)
top_1k_cons_phast_df<-Reduce(rbind,top_1k_cons_phast)
top_1k_cons_phyp_df<-Reduce(rbind,top_1k_cons_phyp)
top_1k_cons_map_df<-Reduce(rbind,top_1k_cons_map)

mapp<-ggplot(top_10k_cons_lecif_df,aes(y=score,x=annot,fill=annot))+geom_boxplot()+theme_classic()+ylab("LECIF score")+xlab("")
mapp2<-ggplot(top_10k_cons_phast_df,aes(y=score,x=celltype,fill=annot))+geom_boxplot()+theme_classic()
mapp3<-ggplot(top_10k_cons_phyp_df,aes(y=score,x=celltype,fill=annot))+geom_boxplot()+theme_classic()+ylab("PhyloP score")+xlab("")


mapp|mapp2|mapp3

#did it with top 1000 sites as well and included Multimap 
write.table(top_1k_cons_map_df,row.names = T,col.names = T,sep="\t",quote=F,file = "/home/torkenczyk/H_M_chromatin_atlas/human_data/Multimap_cons_1k.sites.txt")
write.table(top_1k_cons_phyp_df,row.names = T,col.names = T,sep="\t",quote=F,file = "/home/torkenczyk/H_M_chromatin_atlas/human_data/Phylop_cons_1k.sites.txt")
write.table(top_1k_cons_phast_df,row.names = T,col.names = T,sep="\t",quote=F,file = "/home/torkenczyk/H_M_chromatin_atlas/human_data/Phast_cons_1k.sites.txt")
write.table(top_1k_cons_lecif_df,row.names = T,col.names = T,sep="\t",quote=F,file="/home/torkenczyk/H_M_chromatin_atlas/human_data/Lesik_cons_1k.sites.txt")

ggplot(top_1k_cons_lecif_df,aes(y=score,x=annot,fill=annot))+geom_boxplot()+theme_classic()+ylab("LECIF score")+xlab("")


library(ggpubr)

# Visualize: Specify the comparisons you want
my_comparisons <- list( c("Mouse", "Conserved"),c("Conserved","Human"))
p_phast<-ggboxplot(top_1k_cons_phast_df, x = "annot",fill="annot" ,y = "score", palette = "jco")+ 
  stat_compare_means(comparisons = my_comparisons)+ # Add pairwise comparisons p-value
  stat_compare_means(label.y = 1.1)+ylab("PHAST score")

p_phylop<-ggboxplot(top_1k_cons_phyp_df, x = "annot",fill="annot" ,y = "score", palette = "jco")+ 
  stat_compare_means(comparisons = my_comparisons)+ # Add pairwise comparisons p-value
  stat_compare_means(label.y = 1.1)+ylab("PhyloP score")

p_lecif<-ggboxplot(top_1k_cons_lecif_df, x = "annot",fill="annot" ,y = "score", palette = "jco")+ 
  stat_compare_means(comparisons = my_comparisons)+ # Add pairwise comparisons p-value
  stat_compare_means(label.y = 1.1)+ylab("LECIF score")

wrap_plots(list(p_top5mot,p_phast,p_phylop,p_lecif),ncol=2,nrow = 2)


```


#now test if these DA sites are really DA
```{r}
library(chromVAR)
library(motifmatchr)
library(Matrix)
library(SummarizedExperiment)
library(BiocParallel)
library("BSgenome.Hsapiens.UCSC.hg38")
set.seed(2017)

#human_all_atac<-readRDS("/home/torkenczyk/Human_only_minimal_for_DA.rds")
#mouse_select_atac<-readRDS("/home/torkenczyk/Mouse_only_minimal_for_DA.rds")
have_reads_h<-human_all_atac[["cre"]][[]][human_all_atac[["cre"]][[]]$count>0,]
have_reads_m<-mouse_select_atac[["cre"]][[]][mouse_select_atac[["cre"]][[]]$count>0,]
#have_reads_m<-mouse_select_atac2[["peaks"]][[]][mouse_select_atac2[["peaks"]][[]]$count>0,] #if MM9


human_matched_h_hash<-list()
human_matched_m_hash<-list()
mouse_matched_m_hash<-list()
mouse_matched_h_hash<-list()
human_inters_matched_hash<-list()
mouse_inters_matched_hash<-list()

for (i in (levels(as.factor(markers_h$group)))) {
#clusth<-da.filt.human[da.filt.human$group==i,]$feature
#clustm<-da.filt.mouse[da.filt.mouse$group==i,]$feature
#hmatched<-row.names(have_reads_h) %in% clusth 
#mmatched<-row.names(have_reads_m) %in% clustm
#hda<-da.filt.human[da.filt.human$group==i,]
#mda<-da.filt.mouse[da.filt.mouse$group==i,]
#clusth<-head(hda[with(hda, order(-logFC)),],n=1000)$feature
#clustm<-head(mda[with(mda, order(-logFC)),],n=1000)$feature


#unint_ist_m<-subset(clustm, !(clustm %in% clusth))
#unint_ist_h<-subset(clusth, !(clusth %in% clustm))

unint_ist_m<-mouse_DA[[i]]$feature
unint_ist_h<-human_DA[[i]]$feature # IF orig

#unint_ist_m<-mouse_DA[[i]]$feature_mm9 # IF MM9
#unint_ist_h<-human_DA[[i]]$feature_mm9 # IF MM9

hmatched<-row.names(have_reads_h) %in% unint_ist_h
hmatched_m<-row.names(have_reads_h) %in% unint_ist_m
mmatched<-row.names(have_reads_m) %in% unint_ist_m
mmatched_h<-row.names(have_reads_m) %in% unint_ist_h

#himatched<-row.names(have_reads_h) %in% intersect(clusth,clustm)
himatched<-row.names(have_reads_h) %in% shared_DA[[i]]$feature
#mimatched<-row.names(have_reads_m) %in% intersect(clusth,clustm)

#mimatched<-row.names(have_reads_m) %in% shared_DA[[i]]$feature_mm9  #IF mm9
mimatched<-row.names(have_reads_m) %in% shared_DA[[i]]$feature

human_matched_h_hash[[i]]<-hmatched
human_matched_m_hash[[i]]<-hmatched_m
mouse_matched_m_hash[[i]]<-mmatched
mouse_matched_h_hash[[i]]<-mmatched_h

human_inters_matched_hash[[i]]<-himatched
mouse_inters_matched_hash[[i]]<-mimatched
}



human_matched_h_df <- data.frame(matrix(unlist(human_matched_h_hash), ncol =length(human_matched_h_hash)))
names(human_matched_h_df)<-names(human_matched_h_hash)
human_matched_m_df <- data.frame(matrix(unlist(human_matched_m_hash), ncol =length(human_matched_m_hash)))
names(human_matched_m_df)<-names(human_matched_m_hash)
mouse_matched_m_df <- data.frame(matrix(unlist(mouse_matched_m_hash), ncol=length(mouse_matched_m_hash)))
names(mouse_matched_m_df)<-names(mouse_matched_m_hash)
mouse_matched_h_df <- data.frame(matrix(unlist(mouse_matched_h_hash), ncol=length(mouse_matched_h_hash)))
names(mouse_matched_h_df)<-names(mouse_matched_h_hash)


#now intersected
human_inters_matched_df <- data.frame(matrix(unlist(human_inters_matched_hash), ncol =length(human_inters_matched_hash)))
names(human_inters_matched_df)<-names(human_inters_matched_hash)
mouse_inters_matched_df <- data.frame(matrix(unlist(mouse_inters_matched_hash), ncol=length(mouse_inters_matched_hash)))
names(mouse_inters_matched_df)<-names(mouse_inters_matched_hash)


#human in human
rowRanges<-StringToGRanges(row.names(have_reads_h))
anno_h_h <- getAnnotations(annotations = human_matched_h_df, rowRanges = rowRanges)
fragments_h <- SummarizedExperiment(assays = list(counts = GetAssayData(human_all_atac, assay = "cre", slot = "counts")[row.names(have_reads_h),]), rowRanges = rowRanges)
fragments_h <- filterPeaks(fragments_h, non_overlapping = TRUE)
fragments_h <- addGCBias(fragments_h, genome = BSgenome.Hsapiens.UCSC.hg38)
dev_h_h <- computeDeviations(object = fragments_h, annotations = anno_h_h)

#human in mouse
rowRanges<-StringToGRanges(row.names(have_reads_h))
anno_h_m <- getAnnotations(annotations = human_matched_m_df, rowRanges = rowRanges)
fragments_h <- SummarizedExperiment(assays = list(counts = GetAssayData(human_all_atac, assay = "cre", slot = "counts")[row.names(have_reads_h),]), rowRanges = rowRanges)
fragments_h <- filterPeaks(fragments_h, non_overlapping = TRUE)
fragments_h <- addGCBias(fragments_h, genome = BSgenome.Hsapiens.UCSC.hg38)
dev_h_m <- computeDeviations(object = fragments_h, annotations = anno_h_m)

#in case runs mm9
#dev_h_h<-dev_h
#dev_h_m<-dev_h

#human mouse intersect
rowRanges<-StringToGRanges(row.names(have_reads_h))
anno_h <- getAnnotations(annotations = human_inters_matched_df, rowRanges = rowRanges)
fragments_h <- SummarizedExperiment(assays = list(counts = GetAssayData(human_all_atac, assay = "cre", slot = "counts")[row.names(have_reads_h),]), rowRanges = rowRanges)
fragments_h <- filterPeaks(fragments_h, non_overlapping = TRUE)
fragments_h <- addGCBias(fragments_h, genome = BSgenome.Hsapiens.UCSC.hg38)
dev_h_i <- computeDeviations(object = fragments_h, annotations = anno_h)

#mouse in mouse

rowRanges<-StringToGRanges(row.names(have_reads_m))
anno_m_m <- getAnnotations(annotations = mouse_matched_m_df, rowRanges = rowRanges)
#mouse select atac2 if mm9
#fragments_m <- SummarizedExperiment(assays = list(counts = GetAssayData(mouse_select_atac2, assay = "peaks", slot = "counts")[row.names(have_reads_m),]), rowRanges = rowRanges)
fragments_m <- SummarizedExperiment(assays = list(counts = GetAssayData(mouse_select_atac, assay = "cre", slot = "counts")[row.names(have_reads_m),]), rowRanges = rowRanges)
fragments_m <- filterPeaks(fragments_m, non_overlapping = TRUE)
#fragments_m <- addGCBias(fragments_m, genome = BSgenome.Mmusculus.UCSC.mm9)
fragments_m <- addGCBias(fragments_m, genome = BSgenome.Hsapiens.UCSC.hg38)
dev_m_m <- computeDeviations(object = fragments_m, annotations = anno_m_m)
#dev_m_m<-dev_m
#dev_m_h<-dev_m

#mouse in human
rowRanges<-StringToGRanges(row.names(have_reads_m))
anno_m_h <- getAnnotations(annotations = mouse_matched_h_df, rowRanges = rowRanges)
fragments_m <- SummarizedExperiment(assays = list(counts = GetAssayData(mouse_select_atac, assay = "cre", slot = "counts")[row.names(have_reads_m),]), rowRanges = rowRanges)
#fragments_m <- SummarizedExperiment(assays = list(counts = GetAssayData(mouse_select_atac2, assay = "peaks", slot = "counts")[row.names(have_reads_m),]), rowRanges = rowRanges)
fragments_m <- filterPeaks(fragments_m, non_overlapping = TRUE)
#fragments_m <- addGCBias(fragments_m, genome = BSgenome.Mmusculus.UCSC.mm9)
fragments_m <- addGCBias(fragments_m, genome = BSgenome.Hsapiens.UCSC.hg38)
dev_m_h <- computeDeviations(object = fragments_m, annotations = anno_m_h)

#intersecting in mouse
rowRanges<-StringToGRanges(row.names(have_reads_m))
anno_m <- getAnnotations(annotations = mouse_inters_matched_df, rowRanges = rowRanges)
fragments_m <- SummarizedExperiment(assays = list(counts = GetAssayData(mouse_select_atac, assay = "cre", slot = "counts")[row.names(have_reads_m),]), rowRanges = rowRanges)
#fragments_m <- SummarizedExperiment(assays = list(counts = GetAssayData(mouse_select_atac2, assay = "peaks", slot = "counts")[row.names(have_reads_m),]), rowRanges = rowRanges)
fragments_m <- filterPeaks(fragments_m, non_overlapping = TRUE)
#fragments_m <- addGCBias(fragments_m, genome = BSgenome.Mmusculus.UCSC.mm9)
fragments_m <- addGCBias(fragments_m, genome = BSgenome.Hsapiens.UCSC.hg38)
dev_m_i <- computeDeviations(object = fragments_m, annotations = anno_m)



chromvar.hz <- SummarizedExperiment::assays(dev_h_m)[[2]]
#rownames(x = chromvar.hz) <- colnames(x = anno_h)
human_all_atac[["Deviation_DA_mouse"]] <- CreateAssayObject(data = chromvar.hz)
chromvar.hz <- SummarizedExperiment::assays(dev_h_h)[[2]]
#rownames(x = chromvar.hz) <- colnames(x = anno_h)
human_all_atac[["Deviation_DA_human"]] <- CreateAssayObject(data = chromvar.hz)




DefaultAssay(human_all_atac)<- "Deviation_DA_human"
p1<-RidgePlot(human_all_atac, features = row.names(human_all_atac), ncol = 4)
DefaultAssay(human_all_atac)<- "Deviation_DA_mouse"
p2<-RidgePlot(human_all_atac, features = row.names(human_all_atac), ncol = 4)
#
pdf(file = "./plots/Deviation_DA_human_in_human.pdf",width = 30,height=25)
p1
dev.off()

pdf(file= "./plots/Deviation_DA_mouse_in_human.pdf",width = 30,height=25)
p2
dev.off()


chromvar.hz <- SummarizedExperiment::assays(dev_m_m)[[2]]
#rownames(x = chromvar.hz) <- colnames(x = anno_h)
mouse_select_atac[["Deviation_DA_mouse"]] <- CreateAssayObject(data = chromvar.hz)
chromvar.hz <- SummarizedExperiment::assays(dev_m_h)[[2]]
mouse_select_atac[["Deviation_DA_human"]] <- CreateAssayObject(data = chromvar.hz)

DefaultAssay(mouse_select_atac)<-"Deviation_DA_mouse"
p1b<-RidgePlot(mouse_select_atac, features = row.names(human_all_atac), ncol = 4)
DefaultAssay(mouse_select_atac)<-"Deviation_DA_human"
p2b<-RidgePlot(mouse_select_atac, features = row.names(human_all_atac), ncol = 4)


chromvar.hz <- SummarizedExperiment::assays(dev_h_i)[[2]]
#rownames(x = chromvar.hz) <- colnames(x = anno_h)
human_all_atac[["Deviation_DA_int"]] <- CreateAssayObject(data = chromvar.hz)

chromvar.hz <- SummarizedExperiment::assays(dev_m_i)[[2]]
#rownames(x = chromvar.hz) <- colnames(x = anno_h)
mouse_select_atac[["Deviation_DA_int"]] <- CreateAssayObject(data = chromvar.hz)

DefaultAssay(mouse_select_atac)<-"Deviation_DA_int"

p1c<-RidgePlot(mouse_select_atac, features = row.names(mouse_select_atac), ncol = 4)

DefaultAssay(human_all_atac)<-"Deviation_DA_int"

p2c<-RidgePlot(human_all_atac, features = row.names(human_all_atac), ncol = 4)

p1


```

#genehancer, chromHMM and distance metrics of these sites

```{r}
#do comparison plot of where things lie
table(PNFIN$type)
table(PHMIN$type)

test<-StringToGRanges(mouse_DA$`B-lymphocytes`$feature_hg38_universal)

library("TxDb.Hsapiens.UCSC.hg38.knownGene")
library("org.Hs.eg.db")

load(file="/brahms/torkenczyk/H_M_storage/analysis/objects/DA_info/Shared.bw.species.DA.RData")
load(file="/brahms/torkenczyk/H_M_storage/analysis/objects/DA_info/Mouse_only.bw.species.DA.RData")
load(file="/brahms/torkenczyk/H_M_storage/analysis/objects/DA_info/Human_only.bw.species.DA.RData")

human_10_DA
mouse_10_DA
shared_10_DA

annotateRegions <- function(
  querygranges,
  txdb,
  annoDb,
  ...
){
  # Check depedencies
  if(! "ChIPseeker" %in% installed.packages()){
    stop('Please, install ChIPseeker: \n source("https://bioconductor.org/biocLite.R") \nbiocLite("ChIPseeker")')
  } else {
    require(ChIPseeker)
  }
  
  regions <- querygranges
  #regionAnno <- as.data.frame(annotatePeak(regions, TxDb=txdb, annoDb=annoDb, ...))
  regionAnno <- annotatePeak(regions, TxDb=txdb, annoDb=annoDb,tssRegion=c(-500, 500))
  #regionAnno[grep("Exon", regionAnno$annotation), "annotation"] <- "Exon"
 # regionAnno[grep("Intron", regionAnno$annotation), "annotation"] <- "Intron"
  #rownames(regionAnno) <- regionAnno$regionNames
  #regionAnno <- regionAnno[rownames(object.region.data), !(colnames(regionAnno) %in% c("regionNames", "strand"))]
  return(regionAnno)
}

results_stats<-data.frame(Feature=character(),Frequency=double(),celltype=character(),annot=character())
for (i in names(shared_DA)){
print(i)
test<-StringToGRanges(shared_DA[[i]]$feature_hg38_universal)
out_test<-annotateRegions(sort(test),txdb = TxDb.Hsapiens.UCSC.hg38.knownGene,annoDb = "org.Hs.eg.db")    
out_test<-as.data.frame(out_test@annoStat)
out_test$celltype=i
out_test$annot<-"shared"
results_stats<-rbind(results_stats,out_test)

test<-StringToGRanges(mouse_DA[[i]]$feature_hg38_universal)
out_test<-annotateRegions(sort(test),txdb = TxDb.Hsapiens.UCSC.hg38.knownGene,annoDb = "org.Hs.eg.db")    
out_test<-as.data.frame(out_test@annoStat)
out_test$celltype=i
out_test$annot<-"mouse"
results_stats<-rbind(results_stats,out_test)

test<-StringToGRanges(human_DA[[i]]$feature_hg38_universal)
out_test<-annotateRegions(sort(test),txdb = TxDb.Hsapiens.UCSC.hg38.knownGene,annoDb = "org.Hs.eg.db")    
out_test<-as.data.frame(out_test@annoStat)
out_test$celltype=i
out_test$annot<-"human"
results_stats<-rbind(results_stats,out_test)

}

results_stats$combined_annot<-paste(results_stats$celltype,results_stats$annot,sep="_")

ggplot(data = results_stats,aes(x=Feature,fill=Frequency,y=combined_annot))+geom_tile()

library(reshape2)
acast(results_stats, Feature~y, value.var="z")

ggplot(data = results_stats,aes(x=Feature,y=Frequency,fill=annot))+geom_boxplot()+theme_classic()
#saved now
#also redid with 10k
results_stats2<-data.frame(Feature=character(),Frequency=double(),celltype=character(),annot=character())
for (i in names(shared_DA)){
print(i)
test<-StringToGRanges(shared_10_DA[[i]],sep = c("-","-"))
out_test<-annotateRegions(sort(test),txdb = TxDb.Hsapiens.UCSC.hg38.knownGene,annoDb = "org.Hs.eg.db")    
out_test<-as.data.frame(out_test@annoStat)
out_test$celltype=i
out_test$annot<-"shared"
results_stats2<-rbind(results_stats2,out_test)

test<-StringToGRanges(mouse_10_DA[[i]])
out_test<-annotateRegions(sort(test),txdb = TxDb.Hsapiens.UCSC.hg38.knownGene,annoDb = "org.Hs.eg.db")    
out_test<-as.data.frame(out_test@annoStat)
out_test$celltype=i
out_test$annot<-"mouse"
results_stats2<-rbind(results_stats2,out_test)

test<-StringToGRanges(human_10_DA[[i]])
out_test<-annotateRegions(sort(test),txdb = TxDb.Hsapiens.UCSC.hg38.knownGene,annoDb = "org.Hs.eg.db")    
out_test<-as.data.frame(out_test@annoStat)
out_test$celltype=i
out_test$annot<-"human"
results_stats2<-rbind(results_stats2,out_test)

}

results_stats2$combined_annot<-paste(results_stats2$celltype,results_stats2$annot,sep="_")
ggplot(data = results_stats2,aes(x=Feature,fill=Frequency,y=combined_annot))+geom_tile()
ggplot(data = results_stats2,aes(x=Feature,y=Frequency,fill=annot))+geom_boxplot()+theme_classic()
#end of 10k


#with TSS approach
tss.positions_hg38 <- GetTSSPositions(ranges = Annotation(human_all_atac))
tss.positions_mouse <- GetTSSPositions(ranges = Annotation(mouse_select_atac))

genehancer<-read.table("/brahms/torkenczyk/H_M_storage/analysis/conservation/hg38_genehancer.txt",header = F)
genehancerloc<-StringToGRanges(paste(genehancer$V1,genehancer$V2,genehancer$V3,sep = "-"),sep = c("-","-"))

genehancer_list<-list()
distances_list<-list()
for (i in names(shared_DA)){
print(i)
shared_sites<-StringToGRanges(shared_DA[[i]]$feature_hg38_universal)
human_sites<-StringToGRanges(human_DA[[i]]$feature_hg38_universal)
mouse_sites<-StringToGRanges(mouse_DA[[i]]$mm9_lifted_mm10peak_mouse)
mouse_sites_hg38<-StringToGRanges(mouse_DA[[i]]$feature_hg38_universal)
 
 
shared_dist<-distanceToNearest(shared_sites,tss.positions_hg38)
shared_dist<-shared_dist@elementMetadata$distance
human_dist<-distanceToNearest(human_sites,tss.positions_hg38)  
human_dist<-human_dist@elementMetadata$distance
mouse_dist<-distanceToNearest(mouse_sites,tss.positions_mouse)  
mouse_dist<-mouse_dist@elementMetadata$distance

distances_list[[i]]<-data.frame(shared=shared_dist,human=human_dist,mouse=mouse_dist)

#genehancer shared
shared_genehancerloc<-subjectHits(findOverlaps(shared_sites,genehancerloc))
shared_query<-queryHits(findOverlaps(shared_sites,genehancerloc))
genehancer_select_sh<-genehancer[shared_genehancerloc,]
genehancer_select_sh$original_region<-shared_DA[[i]]$feature_hg38_universal[shared_query]
shared_genehancerloc<-subjectHits(findOverlaps(shared_sites,genehancerloc))
shared_query<-queryHits(findOverlaps(shared_sites,genehancerloc))
genehancer_select_sh<-genehancer[shared_genehancerloc,]
genehancer_select_sh$original_region<-shared_DA[[i]]$feature_hg38_universal[shared_query]
#genehancer human
human_genehancerloc<-subjectHits(findOverlaps(human_sites,genehancerloc))
human_query<-queryHits(findOverlaps(human_sites,genehancerloc))
genehancer_select_hu<-genehancer[human_genehancerloc,]
genehancer_select_hu$original_region<-human_DA[[i]]$feature_hg38_universal[human_query]
human_genehancerloc<-subjectHits(findOverlaps(human_sites,genehancerloc))
human_query<-queryHits(findOverlaps(human_sites,genehancerloc))
genehancer_select_hu<-genehancer[human_genehancerloc,]
genehancer_select_hu$original_region<-human_DA[[i]]$feature_hg38_universal[human_query]
#genehancer mouse
mouse_genehancerloc<-subjectHits(findOverlaps(mouse_sites_hg38,genehancerloc))
mouse_query<-queryHits(findOverlaps(mouse_sites_hg38,genehancerloc))
genehancer_select_mo<-genehancer[mouse_genehancerloc,]
genehancer_select_mo$original_region<-mouse_DA[[i]]$feature_hg38_universal[mouse_query]
mouse_genehancerloc<-subjectHits(findOverlaps(mouse_sites_hg38,genehancerloc))
mouse_query<-queryHits(findOverlaps(mouse_sites_hg38,genehancerloc))
genehancer_select_mo<-genehancer[mouse_genehancerloc,]
genehancer_select_mo$original_region<-mouse_DA[[i]]$feature_hg38_universal[mouse_query]

genehancer_list[[i]]<-data.frame(genehancerscore=c(genehancer_select_sh$V6,genehancer_select_hu$V6,mouse=genehancer_select_mo$V6),annot=rep(x = c("shared","human","mouse"),times=c(length(genehancer_select_sh$V6),length(genehancer_select_hu$V6),length(genehancer_select_mo$V6))))



}

all_distances<-bind_rows(distances_list, .id = "cell_type")
all_distances<-melt(all_distances,id.vars = "cell_type")


p<-ggplot(all_distances,aes(x=cell_type,y=value,fill=variable))+geom_boxplot()+theme_classic()


all_genehancer<-bind_rows(genehancer_list, .id = "cell_type")

#do test
library(ggpubr)

# Visualize: Specify the comparisons you want
my_comparisons <- list( c("mouse", "shared"),c("shared","human"))
p_gh<-ggboxplot(all_genehancer, x = "annot",fill="annot" ,y = "genehancerscore", palette = "jco")+ 
  stat_compare_means(comparisons = my_comparisons)+ # Add pairwise comparisons p-value
  stat_compare_means(label.y = 3)+ylab("Genehancer score")


p<-ggplot(all_distances,aes(x=cell_type,y=log10(value+1),fill=variable))+geom_boxplot()+theme_classic()
p<-ggplot(all_distances,aes(x=variable,y=log10(value+1),fill=variable))+geom_boxplot()+theme_classic()

p2<-ggplot(all_genehancer,aes(x=cell_type,y=genehancerscore,fill=annot))+geom_boxplot()+theme_classic()

save(distances_list,file = "Distances_from_TSS.RData")

#CHROM HMM imputed 25 marks and 15 core marks
#https://egg2.wustl.edu/roadmap/data/byFileType/chromhmmSegmentations/ChmmModels/imputed12marks/jointModel/final/
#lets look at pimary B track chromHMM, I count all of the annotations that it overlaps

Prim_B<-read.table("/home/torkenczyk/H_M_chromatin_atlas/chromHMM/core_marks/E032_15_coreMarks_hg38lift_mnemonics.bed.gz")
pn<-Prim_B$V4
Prim_B<-StringToGRanges(paste(Prim_B$V1,Prim_B$V2,Prim_B$V3,sep = "_"),sep = c("_","_"))
Prim_B$annot <- DataFrame(annot = pn)

Shared_B<-StringToGRanges(shared_DA$`B-lymphocytes`$feature_hg38_universal)
Human_B<-StringToGRanges(human_DA$`B-lymphocytes`$feature_hg38_universal)
Mouse_B<-StringToGRanges(mouse_DA$`B-lymphocytes`$feature_hg38_universal)


sharedB<-Prim_B[queryHits(findOverlaps(Prim_B,Shared_B))]
humanB<-Prim_B[queryHits(findOverlaps(Prim_B,Human_B))]
mouseB<-Prim_B[queryHits(findOverlaps(Prim_B,Mouse_B))]

table(sharedB$annot)
table(mouseB$annot)
table(humanB$annot)


Prim_T<-read.table("/home/torkenczyk/H_M_chromatin_atlas/chromHMM/core_marks/E034_15_coreMarks_hg38lift_mnemonics.bed.gz")
pn<-Prim_T$V4
Prim_T<-StringToGRanges(paste(Prim_T$V1,Prim_T$V2,Prim_T$V3,sep = "_"),sep = c("_","_"))
Prim_T$annot <- DataFrame(annot = pn)

Shared_T<-StringToGRanges(shared_DA$`T-lymphocytes`$feature_hg38_universal)
Human_T<-StringToGRanges(human_DA$`T-lymphocytes`$feature_hg38_universal)
Mouse_T<-StringToGRanges(mouse_DA$`T-lymphocytes`$feature_hg38_universal)

sharedT<-Prim_T[queryHits(findOverlaps(Prim_T,Shared_T))]
humanT<-Prim_T[queryHits(findOverlaps(Prim_T,Human_T))]
mouseT<-Prim_T[queryHits(findOverlaps(Prim_T,Mouse_T))]

table(sharedT$annot)
table(mouseT$annot)
table(humanT$annot)

Prim_SM<-read.table("/home/torkenczyk/H_M_chromatin_atlas/chromHMM/core_marks/E076_15_coreMarks_hg38lift_mnemonics.bed.gz")
pn<-Prim_SM$V4
Prim_SM<-StringToGRanges(paste(Prim_SM$V1,Prim_SM$V2,Prim_SM$V3,sep = "_"),sep = c("_","_"))
Prim_SM$annot <- DataFrame(annot = pn)

Shared_SM<-StringToGRanges(shared_DA$`Smooth muscle cells`$feature_hg38_universal)
Human_SM<-StringToGRanges(human_DA$`Smooth muscle cells`$feature_hg38_universal)
Mouse_SM<-StringToGRanges(mouse_DA$`Smooth muscle cells`$feature_hg38_universal)

sharedSM<-Prim_SM[queryHits(findOverlaps(Prim_SM,Shared_SM))]
humanSM<-Prim_SM[queryHits(findOverlaps(Prim_SM,Human_SM))]
mouseSM<-Prim_SM[queryHits(findOverlaps(Prim_SM,Mouse_SM))]

table(sharedSM$annot)
table(mouseSM$annot)
table(humanSM$annot)


Prim_PN<-read.table("/home/torkenczyk/H_M_chromatin_atlas/chromHMM/core_marks/E114_15_coreMarks_hg38lift_mnemonics.bed.gz")
pn<-Prim_PN$V4
Prim_PN<-StringToGRanges(paste(Prim_PN$V1,Prim_PN$V2,Prim_PN$V3,sep = "_"),sep = c("_","_"))
Prim_PN$annot <- DataFrame(annot = pn)

Shared_PN<-StringToGRanges(shared_DA$Pneumocytes$feature_hg38_universal)
Human_PN<-StringToGRanges(human_DA$Pneumocytes$feature_hg38_universal)
Mouse_PN<-StringToGRanges(mouse_DA$Pneumocytes$feature_hg38_universal)

sharedPN<-Prim_PN[queryHits(findOverlaps(Prim_PN,Shared_PN))]
humanPN<-Prim_PN[queryHits(findOverlaps(Prim_PN,Human_PN))]
mousePN<-Prim_PN[queryHits(findOverlaps(Prim_PN,Mouse_PN))]

table(sharedPN$annot)
table(mousePN$annot)
table(humanPN$annot)

#For endothelial cells and cardiomyocites I use heart

Prim_CR<-read.table("/home/torkenczyk/H_M_chromatin_atlas/chromHMM/core_marks/E095_15_coreMarks_hg38lift_mnemonics.bed.gz")
pn<-Prim_CR$V4
Prim_CR<-StringToGRanges(paste(Prim_CR$V1,Prim_CR$V2,Prim_CR$V3,sep = "_"),sep = c("_","_"))
Prim_CR$annot <- DataFrame(annot = pn)

Shared_CR<-StringToGRanges(shared_DA$Cardiomyocytes$feature_hg38_universal)
Human_CR<-StringToGRanges(human_DA$Cardiomyocytes$feature_hg38_universal)
Mouse_CR<-StringToGRanges(mouse_DA$Cardiomyocytes$feature_hg38_universal)

sharedCR<-Prim_CR[queryHits(findOverlaps(Prim_CR,Shared_CR))]
humanCR<-Prim_CR[queryHits(findOverlaps(Prim_CR,Human_CR))]
mouseCR<-Prim_CR[queryHits(findOverlaps(Prim_CR,Mouse_CR))]

table(sharedCR$annot)
table(mouseCR$annot)
table(humanCR$annot)


Shared_END<-StringToGRanges(shared_DA$`Endothelial cells`$feature_hg38_universal)
Human_END<-StringToGRanges(human_DA$`Endothelial cells`$feature_hg38_universal)
Mouse_END<-StringToGRanges(mouse_DA$`Endothelial cells`$feature_hg38_universal)

sharedEND<-Prim_CR[queryHits(findOverlaps(Prim_CR,Shared_END))]
humanEND<-Prim_CR[queryHits(findOverlaps(Prim_CR,Human_END))]
mouseEND<-Prim_CR[queryHits(findOverlaps(Prim_CR,Mouse_END))]

table(sharedEND$annot)
table(mouseEND$annot)
table(humanEND$annot)



#fibroblast comp 


Prim_FB<-read.table("/home/torkenczyk/H_M_chromatin_atlas/chromHMM/core_marks/E128_15_coreMarks_hg38lift_mnemonics.bed.gz")
pn<-Prim_FB$V4
Prim_FB<-StringToGRanges(paste(Prim_FB$V1,Prim_FB$V2,Prim_FB$V3,sep = "_"),sep = c("_","_"))
Prim_FB$annot <- DataFrame(annot = pn)


Shared_FB<-StringToGRanges(shared_DA$Fibroblasts$feature_hg38_universal)
Human_FB<-StringToGRanges(human_DA$Fibroblasts$feature_hg38_universal)
Mouse_FB<-StringToGRanges(mouse_DA$Fibroblasts$feature_hg38_universal)

sharedFB<-Prim_FB[queryHits(findOverlaps(Prim_FB,Shared_FB))]
humanFB<-Prim_FB[queryHits(findOverlaps(Prim_FB,Human_FB))]
mouseFB<-Prim_FB[queryHits(findOverlaps(Prim_FB,Mouse_FB))]

table(sharedFB$annot)
table(mouseFB$annot)
table(humanFB$annot)

Shared_MF<-StringToGRanges(shared_DA$Myofibroblasts$feature_hg38_universal)
Human_MF<-StringToGRanges(human_DA$Myofibroblasts$feature_hg38_universal)
Mouse_MF<-StringToGRanges(mouse_DA$Myofibroblasts$feature_hg38_universal)

sharedMF<-Prim_FB[queryHits(findOverlaps(Prim_FB,Shared_MF))]
humanMF<-Prim_FB[queryHits(findOverlaps(Prim_FB,Human_MF))]
mouseMF<-Prim_FB[queryHits(findOverlaps(Prim_FB,Mouse_MF))]

table(sharedMF$annot)
table(mouseMF$annot)
table(humanMF$annot)

#colonic mucosa for enterocytes and goblet cells

Prim_ENT<-read.table("/home/torkenczyk/H_M_chromatin_atlas/chromHMM/core_marks/E075_15_coreMarks_hg38lift_mnemonics.bed.gz")
pn<-Prim_ENT$V4
Prim_ENT<-StringToGRanges(paste(Prim_ENT$V1,Prim_ENT$V2,Prim_ENT$V3,sep = "_"),sep = c("_","_"))
Prim_ENT$annot <- DataFrame(annot = pn)


Shared_ENT<-StringToGRanges(shared_DA$Enterocytes$feature_hg38_universal)
Human_ENT<-StringToGRanges(human_DA$Enterocytes$feature_hg38_universal)
Mouse_ENT<-StringToGRanges(mouse_DA$Enterocytes$feature_hg38_universal)

sharedENT<-Prim_ENT[queryHits(findOverlaps(Prim_ENT,Shared_ENT))]
humanENT<-Prim_ENT[queryHits(findOverlaps(Prim_ENT,Human_ENT))]
mouseENT<-Prim_ENT[queryHits(findOverlaps(Prim_ENT,Mouse_ENT))]

table(sharedENT$annot)
table(mouseENT$annot)
table(humanENT$annot)

Shared_GOB<-StringToGRanges(shared_DA$`Goblet cells`$feature_hg38_universal)
Human_GOB<-StringToGRanges(human_DA$`Goblet cells`$feature_hg38_universal)
Mouse_GOB<-StringToGRanges(mouse_DA$`Goblet cells`$feature_hg38_universal)

sharedGOB<-Prim_ENT[queryHits(findOverlaps(Prim_ENT,Shared_GOB))]
humanGOB<-Prim_ENT[queryHits(findOverlaps(Prim_ENT,Human_GOB))]
mouseGOB<-Prim_ENT[queryHits(findOverlaps(Prim_ENT,Mouse_GOB))]

table(sharedGOB$annot)
table(mouseGOB$annot)
table(humanGOB$annot)

#liver and hepatocytes

Prim_HEP<-read.table("/home/torkenczyk/H_M_chromatin_atlas/chromHMM/core_marks/E066_15_coreMarks_hg38lift_mnemonics.bed.gz")
pn<-Prim_HEP$V4
Prim_HEP<-StringToGRanges(paste(Prim_HEP$V1,Prim_HEP$V2,Prim_HEP$V3,sep = "_"),sep = c("_","_"))
Prim_HEP$annot <- DataFrame(annot = pn)


Shared_HEP<-StringToGRanges(shared_DA$Hepatocytes$feature_hg38_universal)
Human_HEP<-StringToGRanges(human_DA$Hepatocytes$feature_hg38_universal)
Mouse_HEP<-StringToGRanges(mouse_DA$Hepatocytes$feature_hg38_universal)

sharedHEP<-Prim_HEP[queryHits(findOverlaps(Prim_HEP,Shared_HEP))]
humanHEP<-Prim_HEP[queryHits(findOverlaps(Prim_HEP,Human_HEP))]
mouseHEP<-Prim_HEP[queryHits(findOverlaps(Prim_HEP,Mouse_HEP))]

table(sharedHEP$annot)
table(mouseHEP$annot)
table(humanHEP$annot)

#monocytes and macrophages

Prim_MAC<-read.table("/home/torkenczyk/H_M_chromatin_atlas/chromHMM/core_marks/E124_15_coreMarks_hg38lift_mnemonics.bed.gz")
pn<-Prim_MAC$V4
Prim_MAC<-StringToGRanges(paste(Prim_MAC$V1,Prim_MAC$V2,Prim_MAC$V3,sep = "_"),sep = c("_","_"))
Prim_MAC$annot <- DataFrame(annot = pn)


Shared_MAC<-StringToGRanges(shared_DA$Macrophages$feature_hg38_universal)
Human_MAC<-StringToGRanges(human_DA$Macrophages$feature_hg38_universal)
Mouse_MAC<-StringToGRanges(mouse_DA$Macrophages$feature_hg38_universal)

sharedMAC<-Prim_MAC[queryHits(findOverlaps(Prim_MAC,Shared_MAC))]
humanMAC<-Prim_MAC[queryHits(findOverlaps(Prim_MAC,Human_MAC))]
mouseMAC<-Prim_MAC[queryHits(findOverlaps(Prim_MAC,Mouse_MAC))]

table(sharedMAC$annot)
table(mouseMAC$annot)
table(humanMAC$annot)


#astrocytes and schewann cells

Prim_SCH<-read.table("/home/torkenczyk/H_M_chromatin_atlas/chromHMM/core_marks/E125_15_coreMarks_hg38lift_mnemonics.bed.gz")
pn<-Prim_SCH$V4
Prim_SCH<-StringToGRanges(paste(Prim_SCH$V1,Prim_SCH$V2,Prim_SCH$V3,sep = "_"),sep = c("_","_"))
Prim_SCH$annot <- DataFrame(annot = pn)


Shared_SCH<-StringToGRanges(shared_DA$`Schwann cells`$feature_hg38_universal)
Human_SCH<-StringToGRanges(human_DA$`Schwann cells`$feature_hg38_universal)
Mouse_SCH<-StringToGRanges(mouse_DA$`Schwann cells`$feature_hg38_universal)

sharedSCH<-Prim_SCH[queryHits(findOverlaps(Prim_SCH,Shared_SCH))]
humanSCH<-Prim_SCH[queryHits(findOverlaps(Prim_SCH,Human_SCH))]
mouseSCH<-Prim_SCH[queryHits(findOverlaps(Prim_SCH,Mouse_SCH))]

table(sharedSCH$annot)
table(mouseSCH$annot)
table(humanSCH$annot)


#I did the following block with shared mouse and human

BS=data.frame(table(sharedB$annot),annot=rep("B-lymphocytes",times=length(table(sharedB$annot))))
MAC=data.frame(table(sharedMAC$annot),annot=rep("Macrophages",times=length(table(sharedMAC$annot))))
T=data.frame(table(sharedT$annot),annot=rep("T-lymphocytes",times=length(table(sharedT$annot))))
ENT=data.frame(table(sharedENT$annot),annot=rep("Enterocytes",times=length(table(sharedENT$annot))))
GOB=data.frame(table(sharedGOB$annot),annot=rep('Goblet cells',times=length(table(sharedGOB$annot))))
HEP=data.frame(table(sharedHEP$annot),annot=rep("Hepatocytes",times=length(table(sharedHEP$annot))))
CARD=data.frame(table(sharedCR$annot),annot=rep("Cardiomyocytes",times=length(table(sharedCR$annot))))
MYF=data.frame(table(sharedMF$annot),annot=rep("Myofibroblasts",times=length(table(sharedMF$annot))))
FIB=data.frame(table(sharedFB$annot),annot=rep("Fibroblasts",times=length(table(sharedFB$annot))))
PN=data.frame(table(sharedPN$annot),annot=rep("Pneumocytes",times=length(table(sharedPN$annot))))
END=data.frame(table(sharedEND$annot),annot=rep("Endothelial cells",times=length(table(sharedEND$annot))))
SM=data.frame(table(sharedSM$annot),annot=rep("Smooth Muscle cells",times=length(table(sharedSM$annot))))
SCH=data.frame(table(sharedSCH$annot),annot=rep("Schwann cells",times=length(table(sharedSCH$annot))))
all_CMHMM <- rbind(BS,T,MAC,END,SM,CARD,MYF,FIB,END,SM,PN,HEP,GOB,ENT,SCH)


names(all_CMHMM)<-c("state","freq","celltype")

chromHMM_sh<-reshape(all_CMHMM, idvar = "state", timevar = "celltype", direction = "wide")
chromHMM_sh[is.na(chromHMM_sh)]<-0
row.names(chromHMM_sh)<-chromHMM_sh$state
chromHMM_sh$state<-NULL



BS=data.frame(table(mouseB$annot),annot=rep("B-lymphocytes",times=length(table(mouseB$annot))))
MAC=data.frame(table(mouseMAC$annot),annot=rep("Macrophages",times=length(table(mouseMAC$annot))))
T=data.frame(table(mouseT$annot),annot=rep("T-lymphocytes",times=length(table(mouseT$annot))))
ENT=data.frame(table(mouseENT$annot),annot=rep("Enterocytes",times=length(table(mouseENT$annot))))
GOB=data.frame(table(mouseGOB$annot),annot=rep('Goblet cells',times=length(table(mouseGOB$annot))))
HEP=data.frame(table(mouseHEP$annot),annot=rep("Hepatocytes",times=length(table(mouseHEP$annot))))
CARD=data.frame(table(mouseCR$annot),annot=rep("Cardiomyocytes",times=length(table(mouseCR$annot))))
MYF=data.frame(table(mouseMF$annot),annot=rep("Myofibroblasts",times=length(table(mouseMF$annot))))
FIB=data.frame(table(mouseFB$annot),annot=rep("Fibroblasts",times=length(table(mouseFB$annot))))
PN=data.frame(table(mousePN$annot),annot=rep("Pneumocytes",times=length(table(mousePN$annot))))
END=data.frame(table(mouseEND$annot),annot=rep("Endothelial cells",times=length(table(mouseEND$annot))))
SM=data.frame(table(mouseSM$annot),annot=rep("Smooth Muscle cells",times=length(table(mouseSM$annot))))
SCH=data.frame(table(mouseSCH$annot),annot=rep("Schwann cells",times=length(table(mouseSCH$annot))))
all_CMHMM <- rbind(BS,T,MAC,END,SM,CARD,MYF,FIB,END,SM,PN,HEP,GOB,ENT,SCH)
names(all_CMHMM)<-c("state","freq","celltype")

chromHMM_m<-reshape(all_CMHMM, idvar = "state", timevar = "celltype", direction = "wide")

chromHMM_m[is.na(chromHMM_m)]<-0
row.names(chromHMM_m)<-chromHMM_m$state
chromHMM_m$state<-NULL


BS=data.frame(table(humanB$annot),annot=rep("B-lymphocytes",times=length(table(humanB$annot))))
MAC=data.frame(table(humanMAC$annot),annot=rep("Macrophages",times=length(table(humanMAC$annot))))
T=data.frame(table(humanT$annot),annot=rep("T-lymphocytes",times=length(table(humanT$annot))))
ENT=data.frame(table(humanENT$annot),annot=rep("Enterocytes",times=length(table(humanENT$annot))))
GOB=data.frame(table(humanGOB$annot),annot=rep('Goblet cells',times=length(table(humanGOB$annot))))
HEP=data.frame(table(humanHEP$annot),annot=rep("Hepatocytes",times=length(table(humanHEP$annot))))
CARD=data.frame(table(humanCR$annot),annot=rep("Cardiomyocytes",times=length(table(humanCR$annot))))
MYF=data.frame(table(humanMF$annot),annot=rep("Myofibroblasts",times=length(table(humanMF$annot))))
FIB=data.frame(table(humanFB$annot),annot=rep("Fibroblasts",times=length(table(humanFB$annot))))
PN=data.frame(table(humanPN$annot),annot=rep("Pneumocytes",times=length(table(humanPN$annot))))
END=data.frame(table(humanEND$annot),annot=rep("Endothelial cells",times=length(table(humanEND$annot))))
SM=data.frame(table(humanSM$annot),annot=rep("Smooth Muscle cells",times=length(table(humanSM$annot))))
SCH=data.frame(table(humanSCH$annot),annot=rep("Schwann cells",times=length(table(humanSCH$annot))))
all_CMHMM <- rbind(BS,T,MAC,END,SM,CARD,MYF,FIB,END,SM,PN,HEP,GOB,ENT,SCH)






names(all_CMHMM)<-c("state","freq","celltype")
chromHMM_h<-reshape(all_CMHMM, idvar = "state", timevar = "celltype", direction = "wide")


chromHMM_h[is.na(chromHMM_h)]<-0
row.names(chromHMM_h)<-chromHMM_h$state
chromHMM_h$state<-NULL



CH1<-Heatmap(scale(chromHMM_sh))

CH2<-Heatmap(scale(chromHMM_m))

CH3<-Heatmap(scale(chromHMM_h))

CH1+CH3+CH2

chmmlist<-list()
chmmlist[["mouse"]]<-chromHMM_m
chmmlist[["human"]]<-chromHMM_h
chmmlist[["shared"]]<-chromHMM_sh

saveRDS(chmmlist,"ChromHMM_res_core.rds")

```










mouse specific sites
```{r}
previously_annotated_mouse<-read.delim("/brahms/torkenczyk/H_M_storage/Previously_unannotated_mouse.txt",header = T)
mouse<-readRDS("/brahms/torkenczyk/H_M_storage/analysis/objects/Select_mouse_tissues.rds")
human<-readRDS("/brahms/torkenczyk/H_M_storage/analysis/objects/Select_human_tissues.rds")

mismatched_previously_annot_mouse_cells<-row.names(previously_annotated_mouse)
mouse_annot_obj<-subset(mouse,cells=mismatched_previously_annot_mouse_cells)

mouse_annot_obj_end<-subset(mouse,cells=row.names(mouse_annot_obj[[]])[mouse_annot_obj$cell_label=="Endothelial II cells"])
mouse_annot_obj_ent<-subset(mouse,cells=row.names(mouse_annot_obj[[]])[mouse_annot_obj$cell_label=="Enterocytes"])
CoveragePlot(mouse_annot_obj_end,region = "LOXL2")

TilePlot(mouse_annot_obj_end,region = "LOXL2")
TilePlot(mouse_annot_obj_end,region = "DCN")
CoveragePlot(human,region = "DCN")
CoveragePlot(human,region = "LOXL2")

TilePlot(human,region = "DCN")
TilePlot(human,region = "DCN")


TilePlot(mouse_annot_obj_ent,region = "LOXL2")
TilePlot(mouse_annot_obj_ent,region = "HEPACAM2")
TilePlot(mouse_annot_obj_ent,region = "HEPACAM2")

CoveragePlot(human,region = "DCN")
CoveragePlot(human,region = "LOXL2")

TilePlot(human,region = "DCN")
TilePlot(human,region = "DCN")



enmark<-FindAllMarkers(mouse_annot_obj_end,min.pct = 0.01)
entmark<-FindAllMarkers(mouse_annot_obj_ent,min.pct = 0.01)


fbm<-row.names(enmark[enmark$cluster=="Fibroblasts" & enmark$avg_log2FC>0 & enmark$p_val_adj<0.05,])
gcm<-row.names(entmark[entmark$cluster=="Goblet cells" & entmark$avg_log2FC>0 & entmark$p_val_adj<0.05,])
gve<-FindMarkers(mouse_annot_obj_ent,ident.2 = "Enterocytes",ident.1 = "Goblet cells",min.pct = 0.01,only.pos = T)

uniqueandda<-intersect(gcm,row.names(gve))

load("/brahms/torkenczyk/H_M_storage/analysis/objects/DA_info/Shared.bw.species.DA.RData")

genes_cons<-intersect(fbm,shared_DA$Fibroblasts$feature_hg38_universal)

a<-ClosestFeature(mouse_annot_obj_end,regions = StringToGRanges(genes_cons))

genes_cons<-intersect(uniqueandda,shared_DA$`Goblet cells`$feature_hg38_universal)

b<-ClosestFeature(mouse_annot_obj_end,regions = StringToGRanges(genes_cons))

#LOXL2,BMP2,DCN,maybe DUSP1

p1<-CoveragePlot(human,region = "DUSP1")
p2<-TilePlot(mouse_annot_obj_end,region = "DUSP1")

wrap_plots(list(p2,p1),ncol=1,nrow = 2)

p1<-CoveragePlot(human,region = "BMP2")
p2<-TilePlot(mouse_annot_obj_end,region = "BMP2")

wrap_plots(list(p2,p1),ncol=1,nrow = 2)

human$old_ident<-Idents(human)
human <- RenameIdents(object = human, 'Myofibroblasts' = "Other" ,'B-lymphocytes'= "Other", 'Enterocytes'= "Other", 'Pneumocytes'= "Other", 'T-lymphocytes'= "Other", 'Goblet cells'= "Other", 'Schwann cells'= "Other", 'Hepatocytes'= "Other", 'Macrophages'= "Other", 'Cardiomyocytes' = "Other")


p1<-CoveragePlot(human,region = "DCN")

mouse_annot_obj_end$old_ident<-Idents(mouse_annot_obj_end)
mouse_annot_obj_end <- RenameIdents(object = mouse_annot_obj_end, 'Myofibroblasts' = "Other" ,'B-lymphocytes'= "Other", 'Enterocytes'= "Other", 'Pneumocytes'= "Other", 'T-lymphocytes'= "Other", 'Goblet cells'= "Other", 'Schwann cells'= "Other", 'Hepatocytes'= "Other", 'Macrophages'= "Other")
p2<-TilePlot(mouse_annot_obj_end,region = "LOXL2")
p2b<-CoveragePlot(mouse_annot_obj_end,region = "LOXL2",tile.size = 2)
wrap_plots(list(p2b,p2,p1),ncol=1,nrow = 3)

p1<-CoveragePlot(human,region = "CEP55")
p2<-CoveragePlot(mouse_annot_obj_ent,region = "CEP55")

Idents(human)<-human$old_ident


human <- RenameIdents(object = human, 'Myofibroblasts' = "Other" ,'B-lymphocytes'= "Other", 'Fibroblasts'= "Other", 'Pneumocytes'= "Other", 'T-lymphocytes'= "Other", 'Smooth muscle cells'= "Other", 'Schwann cells'= "Other", 'Hepatocytes'= "Other", 'Macrophages'= "Other", 'Cardiomyocytes' = "Other","Endothelial cells"= "Other")
mouse_annot_obj_ent <- RenameIdents(object = mouse_annot_obj_ent, 'Myofibroblasts' = "Other" ,'B-lymphocytes'= "Other", 'Fibroblasts'= "Other", 'Pneumocytes'= "Other", 'T-lymphocytes'= "Other", 'Smooth muscle cells'= "Other", 'Schwann cells'= "Other", 'Hepatocytes'= "Other", 'Macrophages'= "Other", 'Cardiomyocytes' = "Other","Endothelial cells"= "Other")

p1<-CoveragePlot(human,region = "ATOH1",annotation = F,peaks = F,extend.upstream = 5000)
p2<-CoveragePlot(mouse_annot_obj_ent,region = "ATOH1",extend.upstream = 5000)
a<-wrap_plots(list(p1,p2),ncol=1,nrow = 2)
p1b<-CoveragePlot(human,region = "HEPACAM2",extend.upstream = 1000,peaks = F,annotation = F)
p2b<-CoveragePlot(mouse_annot_obj_ent,region = "HEPACAM2",extend.upstream = 1000)
a2<-wrap_plots(list(p1,p2,p1b,p2b),ncol=1,nrow = 4)



```




```{r}

p1<-plot_combined_cross_species(gene = "MYH11",plot_by = "id")
p2<-plot_combined_cross_species(gene = "PAX5",plot_by = "id")
p3<-plot_combined_cross_species(gene = "VIL1",plot_by = "id")
p4<-plot_combined_cross_species(gene = "SFTPB",plot_by = "id")

p5<-plot_combined_cross_species(gene = "IFNG",plot_by = "id")
p6<-plot_combined_cross_species(gene = "ATP2C2",plot_by = "id")
p7<-plot_combined_cross_species(gene = "NID1",plot_by = "id")
p8<-plot_combined_cross_species(gene = "SOX10",plot_by = "id")

A<-wrap_plots(list(p1,p2,p3,p4,p5,p6,p7,p8),ncol=4,nrow = 2)

p9<-plot_combined_cross_species(gene = "ALB",plot_by = "id")
p10<-plot_combined_cross_species(gene = "CD14",plot_by = "id")
p11<-plot_combined_cross_species(gene = "ENG",plot_by = "id")
p12<-plot_combined_cross_species(gene = "MPRIP",plot_by = "id")
p13<-plot_combined_cross_species(gene = "MYH6",plot_by = "id")


A<-wrap_plots(list(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p12,p11,p13),ncol=4,nrow = 4)

a<-plot_combined_cross_species(gene = "NKX-2",plot_by = "id")

```





